version: '3'

services:
  django:
    build:
      context: ./containers
      dockerfile: Dockerfile
    
    container_name: django
    
    ports:
      - "8000:8000"
    
    tty: true

    volumes:
      - ${SRC_PATH}:/root/workspace